FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["ISA/ISA.csproj", "ISA/"]
COPY ["Counter/Counter.csproj", "Counter/"]
RUN dotnet restore "ISA/ISA.csproj"
RUN dotnet restore "Counter/Counter.csproj"

COPY ./ISA/ ISA/.
RUN dotnet publish -c Release -o /app ISA/ISA.csproj 

COPY ./Counter/ Counter/.
RUN dotnet publish -c Release -o /app Counter/Counter.csproj 

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS publish
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "Counter.dll"]