version: "3.6"

services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
     - "5672:5672"
     - "15672:15672"
     - "15692:15692"
     
  ALU:
    build:
      context: ./ALU
      dockerfile: ./ALU/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  Decoder:
    build:
      context: ./Decoder
      dockerfile: ./Decoder/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  Memory:
    build:
      context: ./Memory
      dockerfile: ./Memory/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  RegisterFile:
    build:
      context: ./RegisterFile
      dockerfile: ./RegisterFile/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
