version: "3.6"

services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
     - "5672:5672"
     - "15672:15672"
     - "15692:15692"
     
  alu:
    build:
      context: .
      dockerfile: Dockerfile-ALU
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  decoder:
    build:
      context: .
      dockerfile: Dockerfile-Decoder
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  memory:
    build:
      context: .
      dockerfile: Dockerfile-Memory
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  counter:
    build:
      context: .
      dockerfile: Dockerfile-Counter
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  registerfile:
    build:
      context: .
      dockerfile: Dockerfile-RegisterFile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
